### ISSUE TITLE
Can't use the extension at this moment, I get now:`text-davinci-003` has been deprecated

### ISSUE THREAD

**Issue by arlanbrado** [ai-genie/chatgpt-vscode#150]
### Describe the feature

Full error:
An error occured. ChatGPT error 404: { "error": { "message": "The model `text-davinci-003` has been deprecated, learn more here: https://platform.openai.com/docs/deprecations", "type": "invalid_request_error", "param": null, "code": "model_not_found" } }

**Comment by mfishes** [comment]
also getting this. Changing the model in settings doesn't work.

**Comment by mutantdustbunny** [comment]
The devs need to update the extension, as davinci-003 model has been deprecated, rendering the extension unusable.

**Comment by mfishes** [comment]
if you switch out of the editor view it'll respect the model selected for in the settings. Editor view looks to be borked though.

**Comment by jkaet** [comment]
Any plans to fix this? Or has this project been abandoned?

**Comment by ericasberry** [comment]
First time user checking this project out, and ran into this issue immediately, so I haven't really even been able to evaluate it.   Seeing there's no fix I guess I'll have to move on to something else.

**Comment by teachamantofish** [comment]
First time user here too, and giving up. VSC plugins are generally known for their ease of install and use. But after an hour of screwing around (and seeing this same error), it's not worth it at this time. CoPilot works great and took zero knowledge and time to get up and running.

**Comment by mfishes** [comment]
Not sure if others have tried this, but it works like a charm in conversation view. 
![image](https://github.com/ai-genie/chatgpt-vscode/assets/61524642/4ffc01e1-4634-4b45-914d-978daa7628fb)

**Comment by nageljoe1** [comment]
As of 3/7/2024, this is still not fixed.  Chat works, but the shortcuts do not; they still generate the "deprecated" errors.

This is disappointing.

**Comment by alireza-nasseri-azihub** [comment]
still waiting

**Comment by genieai-info** [comment]
The extension has two views. If you switch between those, it will remember your selection and show you the last mode (Conversation View vs Editor View). FYI.

The editor view was using the legacy text-davinci model. It's deprecated by OpenAI but I just had a chance to address the changes in the extension.

The new models are also now available in v0.0.11 please update your extensions. gpt-4o is set as default. It uses your selected model instead of the deprecated legacy OpenAI model.


![image](https://github.com/ai-genie/chatgpt-vscode/assets/128560534/b61a7b4f-dd58-402d-8c50-456c93cf6538)
