### ISSUE TITLE
Select a language?

### ISSUE THREAD

**Issue by ScottBeeson** [ai-genie/chatgpt-vscode#26]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

If I have an HTML file open and I prompt it to "Write some basic HTML to do x", it creates a new tab and says "Select a language". If I pick HTML, then switch to a javascript file and ask it to write some JavaScript to do something, it goes back to the HTML file.

Is this working as intended? This is my first time using this extension, but I had previously used the deprecated ChatGPT plugin and didn't have any issues with it.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

defaults

**Comment by genieai-info** [comment]
Hi @ScottBeeson, the `Editor View` is a new feature we added on top of the now-deprecated vscode-chatgpt. The idea is for Genie to respond to your prompts in a new editor tab. Instead of creating a new tab for each prompt, Genie will re-use the existing Untitled/New tab for all of your requests. So what you are experiencing is the intended experience.

With auto-language-detection that vs code provides, the new answer's language in the new editor(In your example writing in the previous html file) will be automatically detected by vs code and the language will be changed to that. Make sure you have the auto language detection setting in your vs-code is enabled to fully utilize this feature.

If you see any issues with the experience, please feel free to suggest improvements. But reusing an existing tab for the answers, in our opinion is the best instead of opening a new tab for every prompt. With the vscode's built-in language detection, this experience, to us, is optimal.
