### ISSUE TITLE
How can I make sure API key is always accessible after setting it up?

### ISSUE THREAD

**Issue by liziqiang0523** [ai-genie/chatgpt-vscode#38]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

How can I make sure API key is always accessible after setting it up?

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

gpt-3.5-turbo

**Comment by liziqiang0523** [comment]
HTTP 400 Bad Request. You may have exhausted your OpenAI subscription allowance or have an expired account. You can clear your API Key from VS Code's [secrets storage](https://code.visualstudio.com/api/references/vscode-api#SecretStorage) with Genie: Clear API Key command. Check your allowance and account's expiration date here: https://platform.openai.com/account/usage

{
  "error": {
    "message": "This model's maximum context length is 4097 tokens. However, you requested 4293 tokens (3781 in the messages, 512 in the completion). Please reduce the length of the messages or completion.",
    "type": "invalid_request_error",
    "param": "messages",
    "code": "context_length_exceeded"
  }
}

**Comment by genieai-info** [comment]
You can now use `Change API Key` button on the home page to view/clear/update your API Key. You could also use command `Genie: Clear API Key` to clear your API Key and then ask a question to be prompted to enter a new API Key. VS Code secrets storage won't let you read/copy & paste the entered API Key after it's stored (This is by design by the vscode itself)

Your second question is related to the past conversation being used for historical purposes. in v0.0.5, we decreased the number of messages appended to your conversations when you ask a question. So that you hit that issue late in your conversation (You will hit it likely at some point due to token limitations anyway)

Related to #35 and #37
