### ISSUE TITLE
Conversation History Improvement

### ISSUE THREAD

**Issue by EHMilon** [ai-genie/chatgpt-vscode#46]
### Improvement of conversation history
Including Conversation History is a great feature of **ChatGPT -Genie AI**. But it's hard to find history, because all chat history name is **New Chat**. We can rename the history by editing the **.JSON** file, But it takes a lot of laziness and time to do this. So if you improve this thing it will help to find important chat history.

I have some idea if you like you can implement thous on your lovely **ChatGPT -Genie AI** extension.

1. When we ask something on _ChatGPT official website_, after answering the question, it automatically creates a name on the top of the page and saves the history of the conversation according to the name. **ChatGPT -Genie AI** can also generate a custom name by analyzing the query.

2. In **ChatGPT -Genie AI** extension, you can add an optional option to add conversation name when we press ➕ sign for **New Chat** conversation. If someone wants to change the name, they can add the name, otherwise the conversation history will save **“New Chat”** or **custom name** by analyzing the question.
In the **Geine extension**, above the 💡 idea sign or **Ice breakers** you can create a box to add the name of the conversation and before the ➕ sign “**Geine: Conversation View**” you can replace with the name of the chat history.
![Screenshot 2023-04-02 155323](https://user-images.githubusercontent.com/107425940/229348243-efd78668-3862-4f97-b977-150e38f7ea38.png)

3. ➕ New Chat option is so hard to reach, that's why people don't use that. 

4. **Chat history ID** should be replaced with conversation name, or something easy to understand.

  If you improve chat history name, it will help to find important chat history and save our time.
 
**ChatGPT -Genie AI** Extension is very helpful for developers and also include me. So you and all of you deserve a lot of thanks from us, **take love ❤️💖❤️ from the bottom of my heart**. Wish you all the best and keep doing. Have a good day.

**Comment by genieai-info** [comment]
Thanks for the suggestions @EHMilon, please check out the latest version to see the chat conversation improvements around renaming & removing conversations using the extension's built-in functionality in v0.0.7.

There is already a New chat button in the overflow menu and you can even assign keyboard shortcuts to it since it's a regular vscode command. See below
![image](https://user-images.githubusercontent.com/128560534/229385690-9af85e13-94cf-4eec-8e9a-e6500aef67b1.png)

We'd want to refrain from asking ChatGPT to generate a conversation name for your chat to preserve your tokens(which cost) so it's better if you name them without us implicitly consuming your tokens.

Let us know how you like the new version and you can close the issue if you are good with those. Thanks.

**Comment by EHMilon** [comment]
**Yes,** I found that. But if you replace **“Geine: Conversation View”** by the conversion history name, and add **➕**  button beside **three dots**, then user easily change by **one click**.
**Thanks for answering.**
