### ISSUE TITLE
Unable To Use GPT-4 Models

### ISSUE THREAD

**Issue by cnaples79** [ai-genie/chatgpt-vscode#6]
### Verify it's not a duplicate bug report

- [X] I searched for similar bugs reported on GitHub and nobody has reported a similar issue. <a href="https://github.com/ai-genie/vscode-chatgpt/issues?q=" target="_blank">Search all issuees</a>.
- [X] I read <a href="https://github.com/ai-genie/vscode-chatgpt#troubleshooting" target="_blank">Troubleshooting guide on Readme</a> and there is not a guide on how to solve my problem.

### Describe the Bug

Set Model to GPT-4 or any of it's variants.

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

Default settings with any of the GPT-4 Models do not work. 
Are they suppse to work?? I know gpt4 is only for Plus subscribers, but I'd assume it works with your API if you have Plus. Otherwise why are the GPT4 models included in the extension?

**Comment by genieai-info** [comment]
Hi @cnaples79 - the GPT-4 API is only available via a waitlist, did you sign up here and received the invite? https://openai.com/waitlist/gpt-4-api

ChatGPT Plus on web gives you the access to GPT-4 via web interface, not the API access.

GPT-4 is an available model in the extensions for those who received access to the API. We still made the default model gpt-3.5 since everyone has access to it at the moment. Once GPT-4 is generally available, we will update the default to it. But till then you need to be signed up for it. Thanks

**Comment by cnaples79** [comment]
I have GPT-4 from the Plus subscription. I guess I don't have the API for
it yet.
Should GPT4 work since I have Plus? Or do I need the actual special API
from the waitlist?

**Comment by genieai-info** [comment]
You need your waitlist request to be approved in order to use the GPT-4 via APIs. GPT-4 Plus subscription doesn't grant you that right now.

**Comment by mreduar** [comment]
Hi, I just got approved by the waitlist and immediately went to genie to test it, I can use GPT4, but not GPT4-32k, is there a difference in terms of genie?

**Comment by snoyiatk** [comment]
Is it possible to use GPT-4 with Azure OpenAI services (instead of OpenAI itself)?
It's difficult to understand the relationship between OpenAI & Azure OpenAI [Deployment URL] settings.

**Comment by Doncuppjr** [comment]
gpt-4 API has been at general availability for a while. It's still not working.

**Comment by genieai-info** [comment]
gpt-4 turbo models are now available in the latest version. please check it out.
